version: '3'

services:
  mysql:
    image: mysql
    container_name: sql
    ports: 
      - 8306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /c/Users/TNC/Desktop/dd:/var/lib/mysql
    network_mode: bridge
    command: --innodb-use-native-aio=0
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8800:80
    network_mode: bridge
    container_name: padmin
    links:
      - 'mysql:db'
