version: '3'

services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    ports: 
      - 8080:8080
      - 50000:50000
    volumes:
      - /c/Users/TNC/Desktop/jens:/var/jenkins_home
    network_mode: bridge
